import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "TuistRootManifestFileExample",
    projects: ["."],
    additionalFiles: [
        "Workspace.swift"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled,
        renderMarkdownReadme: false
    )
)
